name: autogen
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - aiofiles==24.1.0
      - alembic==1.16.1
      - annotated-types==0.7.0
      - anthropic==0.52.2
      - anyio==4.9.0
      - autogen-agentchat==0.5.7
      - autogen-core==0.5.7
      - autogen-ext==0.5.7
      - autogenstudio==0.4.2.2
      - azure-ai-agents==1.1.0b1
      - azure-ai-documentintelligence==1.0.2
      - azure-ai-inference==1.0.0b9
      - azure-ai-projects==1.0.0b11
      - azure-common==1.1.28
      - azure-core==1.34.0
      - azure-identity==1.23.0
      - azure-search-documents==11.5.2
      - azure-storage-blob==12.25.1
      - beautifulsoup4==4.13.4
      - cachetools==5.5.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cobble==0.1.4
      - coloredlogs==15.0.1
      - cryptography==45.0.3
      - defusedxml==0.7.1
      - distro==1.9.0
      - dnspython==2.7.0
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - flatbuffers==25.2.10
      - future==1.0.0
      - google-auth==2.40.3
      - google-genai==1.19.0
      - greenlet==3.2.3
      - h11==0.16.0
      - html2text==2025.4.15
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - isodate==0.7.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - jsonref==1.1.0
      - loguru==0.7.3
      - lxml==5.4.0
      - magika==0.6.2
      - mako==1.3.10
      - mammoth==1.9.1
      - markdown-it-py==3.0.0
      - markdownify==1.1.0
      - markitdown==0.1.2
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msal==1.32.3
      - msal-extensions==1.3.1
      - numpy==2.2.6
      - olefile==0.47
      - onnxruntime==1.22.0
      - openai==1.84.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - opentelemetry-api==1.34.0
      - packaging==25.0
      - pandas==2.3.0
      - pdfminer-six==20250506
      - pillow==11.2.1
      - playwright==1.52.0
      - protobuf==5.29.5
      - psycopg==3.2.9
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pydub==0.25.1
      - pyee==13.0.0
      - pygments==2.19.1
      - pyjwt==2.10.1
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rich-toolkit==0.14.7
      - rsa==4.9.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - speechrecognition==3.14.3
      - sqlalchemy==2.0.41
      - sqlmodel==0.0.24
      - starlette==0.46.2
      - sympy==1.14.0
      - tiktoken==0.9.0
      - tomli==2.2.1
      - tqdm==4.67.1
      - typer==0.16.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.3
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - websockets==15.0.1
      - xlrd==2.0.1
      - xlsxwriter==3.2.3
      - youtube-transcript-api==1.0.3
      - zipp==3.23.0
